### ISSUE TITLE
Basic design

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/quaternion#3]
The idea is to follow vecmath's design.

``` Rust
pub type Quaternion<T> = [T; 4]
```
- [x] `add`
- [x] `mul`
- [x] `conj`

**Comment by bvssvni** [comment]
Should we support both quaternions that starts with a real and ends with a real?

**Comment by bvssvni** [comment]
By depending on vecmath, the scalar/vector notation can be used. The law for multiplication is:

![quaternion rules](https://upload.wikimedia.org/math/6/8/7/687f7d10c9876d3194930482368f8df8.png)

**Comment by ruuda** [comment]
Is it worth having an entire crate for such a simple single struct? Why not put it in vecmath?

**Comment by bvssvni** [comment]
@ruud-v-a I like to keep the libraries small and decoupled.

**Comment by ruuda** [comment]
They are not decoupled, quaternion depends on vecmath!

**Comment by bvssvni** [comment]
@ruud-v-a Sorry, my mistake.

**Comment by bvssvni** [comment]
@ruud-v-a Are you on IRC (#rust-gamedev), so we can discuss this?
